version: '3'
services:
  ss_main:
    build:
      context: .
      dockerfile: dkf_server

    container_name: 'ss_server'
    image: 'ss:py'
    command: '-s 172.110.0.2 -p 1090 -k 密码 -m salsa20 --fast-open'
    ports:
    - '0.0.0.0:13366:1090'
    networks:
      bucket_net: {ipv4_address: 172.110.0.2}
    ulimits:
      nproc: 65535
      nofile: {soft: 20000, hard: 40000}

networks:
  bucket_net:
    driver: bridge
    ipam:
      driver: default
      config: [{subnet: 172.110.0.0/24}]
