FROM debian:stretch-slim
WORKDIR /ss
RUN  groupadd -r ss && useradd -r -g ss ss \
    && apt-get update \
    && apt-get upgrade -y \
    && apt install -y shadowsocks-libev \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
