version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
#    network_mode: "bridge"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/nginx/conf.d://etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
      - /opt/www:/var/www
